### ISSUE TITLE
When the code will be available?

### ISSUE THREAD

**Issue by maudzung** [wangguojun2018/CenterNet3d#1]
Hi @wangguojun2018 

Thanks for the interesting paper. Can I ask you when the code will be available?

**Comment by wangguojun2018** [comment]
> Hi @wangguojun2018
> 
> Thanks for the interesting paper. Can I ask you when the code will be available?

It will be available in one week

**Comment by maudzung** [comment]
Thank you @wangguojun2018 

I'm looking forward to seeing the official source code from you.
Does the model run real-time? I have tried to implement the paper, but the **forward pass** for a single sample is taken the time of **~130ms** (around 7 fps) on GTX1080Ti.
Did you develop models with **many classes** such as cars, pedestrians, cyclists,...? In the paper, you mentioned that it's only for the car detection task.

**Comment by maudzung** [comment]
Hi @wangguojun2018 

Thanks for your source code.
Can you disclose the speed of your implementation?
