### ISSUE TITLE
how to prepare the dataset

### ISSUE THREAD

**Issue by jialeli1** [wangguojun2018/CenterNet3d#4]
Hello. 
It is unclear how to prepare the dataset in this project. And in the dataset config (such as configs/_base_/datasets/**kitti-3d-car.py**), you use your own local directory.
I also refer to the README of mmdet3D, but I am still confused about how to prepare the dataset in this project. 
Would you like to provide some instructions?

**Comment by wangguojun2018** [comment]
you should prepare dataset following [mmdetection3d](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/getting_started.md)
