### ISSUE TITLE
KeyError: 'CenterNet3D is not in the detector registry'

### ISSUE THREAD

**Issue by jialeli1** [wangguojun2018/CenterNet3d#5]
Sorry to raise an issue again. 
After I tried to change to my own dataset directory, it started running. But when I run this line 'python tools/train.py ./configs/centernet3d.py', I encountered this problem. 
Thank you again for giving me some tips.

2020-09-07 15:53:01,409 - mmdet - INFO - Set random seed to 0, deterministic: False
Traceback (most recent call last):
  File "tools/train.py", line 173, in <module>
    main()
  File "tools/train.py", line 146, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/lijiale/thirdspace/mmdetection3d/mmdet3d/models/builder.py", line 38, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/lijiale/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmdet/models/builder.py", line 32, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/lijiale/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/utils/registry.py", line 157, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
**KeyError: 'CenterNet3D is not in the detector registry'**

**Comment by wangguojun2018** [comment]
> Sorry to raise an issue again.
> After I tried to change to my own dataset directory, it started running. But when I run this line 'python tools/train.py ./configs/centernet3d.py', I encountered this problem.
> Thank you again for giving me some tips.
> 
> 2020-09-07 15:53:01,409 - mmdet - INFO - Set random seed to 0, deterministic: False
> Traceback (most recent call last):
> File "tools/train.py", line 173, in
> main()
> File "tools/train.py", line 146, in main
> cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
> File "/home/lijiale/thirdspace/mmdetection3d/mmdet3d/models/builder.py", line 38, in build_detector
> return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
> File "/home/lijiale/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmdet/models/builder.py", line 32, in build
> return build_from_cfg(cfg, registry, default_args)
> File "/home/lijiale/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/utils/registry.py", line 157, in build_from_cfg
> f'{obj_type} is not in the {registry.name} registry')
> **KeyError: 'CenterNet3D is not in the detector registry'**

do you clone this repository? I have registry 'CenterNet3D' in [detectors](https://github.com/wangguojun2018/CenterNet3d/blob/master/mmdet3d/models/detectors/__init__.py)

**Comment by jialeli1** [comment]
> > Sorry to raise an issue again.
> > After I tried to change to my own dataset directory, it started running. But when I run this line 'python tools/train.py ./configs/centernet3d.py', I encountered this problem.
> > Thank you again for giving me some tips.
> > 2020-09-07 15:53:01,409 - mmdet - INFO - Set random seed to 0, deterministic: False
> > Traceback (most recent call last):
> > File "tools/train.py", line 173, in
> > main()
> > File "tools/train.py", line 146, in main
> > cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
> > File "/home/lijiale/thirdspace/mmdetection3d/mmdet3d/models/builder.py", line 38, in build_detector
> > return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
> > File "/home/lijiale/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmdet/models/builder.py", line 32, in build
> > return build_from_cfg(cfg, registry, default_args)
> > File "/home/lijiale/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/utils/registry.py", line 157, in build_from_cfg
> > f'{obj_type} is not in the {registry.name} registry')
> > **KeyError: 'CenterNet3D is not in the detector registry'**
> 
> do you clone this repository? I have registry 'CenterNet3D' in [detectors](https://github.com/wangguojun2018/CenterNet3d/blob/master/mmdet3d/models/detectors/__init__.py)

May I talk to you in Chinese?
是的，我也找到你注册了centernet3d的新模块，但在train.py中的build_detector( )https://github.com/wangguojun2018/CenterNet3d/blob/8ba2b5efb6da52fc4ab1f6a062a7b7adddfd2e77/tools/train.py#L145 调用的是我安装的mmdet3d的repo里面的代码，而不是CenterNet3D/mmdet3d/models/builder.py里面的代码，所以出现了“not in the detector registry”的错误。我应该检查什么地方呢？

**Comment by wangguojun2018** [comment]
那你就别安装了，设置好PYTHONPATH环境变量就好



王国军&nbsp; 博士研究生
吉林大学汽车仿真与控制国家重点实验室
地址：吉林省长春市人民大街5988号
邮编：130025
手机：18686349676
邮箱：839977837@qq.com


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangguojun2018/CenterNet3d"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 上午9:42
收件人:&nbsp;"wangguojun2018/CenterNet3d"<CenterNet3d@noreply.github.com&gt;;
抄送:&nbsp;"839977837"<839977837@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wangguojun2018/CenterNet3d] KeyError: 'CenterNet3D is not in the detector registry' (#5)





   
Sorry to raise an issue again.
 After I tried to change to my own dataset directory, it started running. But when I run this line 'python tools/train.py ./configs/centernet3d.py', I encountered this problem.
 Thank you again for giving me some tips.
 2020-09-07 15:53:01,409 - mmdet - INFO - Set random seed to 0, deterministic: False
 Traceback (most recent call last):
 File "tools/train.py", line 173, in
 main()
 File "tools/train.py", line 146, in main
 cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
 File "/home/lijiale/thirdspace/mmdetection3d/mmdet3d/models/builder.py", line 38, in build_detector
 return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
 File "/home/lijiale/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmdet/models/builder.py", line 32, in build
 return build_from_cfg(cfg, registry, default_args)
 File "/home/lijiale/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/utils/registry.py", line 157, in build_from_cfg
 f'{obj_type} is not in the {registry.name} registry')
 KeyError: 'CenterNet3D is not in the detector registry'
  
do you clone this repository? I have registry 'CenterNet3D' in detectors
  
May I talk to you in Chinese?
 是的，我也找到你注册了centernet3d的新模块，但在train.py中的build_detector( )https://github.com/wangguojun2018/CenterNet3d/blob/8ba2b5efb6da52fc4ab1f6a062a7b7adddfd2e77/tools/train.py#L145 调用的是我安装的mmdet3d的repo里面的代码，而不是CenterNet3D/mmdet3d/models/builder.py里面的代码，所以出现了“not in the detector registry”的错误。我应该检查什么地方呢？

**Comment by programmeeer** [comment]
How to solve it?  I have this error continuously - KeyError: 'CenterNet3D is not in the detector registry'

**Comment by shun1267** [comment]
You have to set PYTHONPATH
export PYTHONPATH="the path to CenterNet3d"
